### ISSUE TITLE
Added to travis

### ISSUE THREAD

**Issue by chillu** [silverstripe-australia/advancedworkflow#161]
Its already set up with a `.travis.yml`, and has unit tests, so its a shame that those aren't actually run on CI. Looks like it just takes a owner of the project logging in to travis, going to https://travis-ci.org/australia/silverstripe-advancedworkflow and enabling? /cc @mateusz @ajshort

**Comment by chillu** [comment]
Ping @nyeholt

**Comment by nyeholt** [comment]
It is set up now right? At least - https://travis-ci.org/silverstripe-australia/advancedworkflow exists and the logo is being linked through from the README correctly :)

**Comment by chillu** [comment]
Ah damn, that link in my initial description pointed to the wrong repo ... all good.
