### ISSUE TITLE
Integration with Fluent

### ISSUE THREAD

**Issue by coreyworrell** [silverstripe-australia/advancedworkflow#208]
Hello,

I'm wondering if it is possible to use separate workflow instances (same workflow, different instance) for content that is translated through the [SilverStripe Fluent](https://github.com/tractorcow/silverstripe-fluent) module?

It seems that right now the workflow state is the same for every language version of the page.

Thank you.

**Comment by tractorcow** [comment]
There is a glaring weakness in fluent where there isn't much of a permission model per-locale. Each page is a single entity, and there's no mechanism per-se for referencing a particual page-locale via normal dataobject relations. I'd say this feature is not currently feasible without a lot of work (mostly on the Fluent end).

**Comment by phptek** [comment]
@coreyworrell does @tractorcow's response answer your question? It might pay to raise a ticket in the Fluent issues list and reference this ticket from there, for future reference.

**Comment by coreyworrell** [comment]
@phptek yes, it seems not to be possible with the way Fluent currently works. Thanks for checking.
