### ISSUE TITLE
Scheduled Publishing Job (WorkflowPublishTargetJob) results in broken job

### ISSUE THREAD

**Issue by adunn49** [silverstripe-australia/advancedworkflow#450]
Hi team. I'm writing up this issue that I have spotted. Also, I have noticed that there is a recent pull request (https://github.com/symbiote/silverstripe-advancedworkflow/pull/449) that has been raised , independent of this issue, that should resolve this.

Having enabled the embargo functionality offered by WorkflowEmbargoExpiryExtension, running the scheduled publishing job results in a broken report (though the page does get published as expected). This is a result of extension hooks being added at 5.3.1, without adding the extensible trait to the job class.

**Steps to reproduce**

Create a page, add a scheduled publishing date, and save.
Go to the queued managers job, and note the job labelled 'Scheduled publish ...'.
Run the job (manually by hitting the play button)
Notice the 'broken' job

Job in queue prior to running ...
![Screen Shot 2021-07-19 at 12 20 10 PM](https://user-images.githubusercontent.com/21965646/126091316-3148257b-d500-4717-a540-7860182de1dc.png)

Job in queue after running showing broken state ...
![Screen Shot 2021-07-19 at 12 20 25 PM](https://user-images.githubusercontent.com/21965646/126091328-e068a19c-faa9-4ea2-8c6c-c24f99463f5b.png)

Error added to job messages ...
![Screen Shot 2021-07-19 at 12 20 34 PM](https://user-images.githubusercontent.com/21965646/126091335-bd2cd62b-528d-4265-8f22-40f722c25b0d.png)

**Comment by michalkleiner** [comment]
I believe this has been addressed by #449 but if that's not the case and the issue can still be replicated then please open a new issue.
