### ISSUE TITLE
Incorrect argument order in WorkflowApplicable extension

### ISSUE THREAD

**Issue by satrun77** [silverstripe-australia/advancedworkflow#514]
### Module version(s) affected

6.1.1

### Description

When applying workflow to a page. There is an error related to an incorrect argument for insertBefore

```
[Emergency] Uncaught TypeError: SilverStripe\Forms\FieldList::insertBefore(): Argument #2 ($item) must be of type SilverStripe\Forms\FormField, string given, called in /Users/mo/Sites/cms/vendor/silverstripe/framework/src/Forms/CompositeField.php on line 349
```

### How to reproduce

- Create a new workflow and select a default template
- Fill in all required fields for workflow and save
- Create another workflow
- Go to Pages
- Edit a page
- Go to settings
- Select the workflow you have created in `Applied Workflow`
- Select the second workflow in `Additional Workflows`
- Save and go back to the Content tab
- There is an error about the incorrect argument. You may have to check network tab in console

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
For future reference:
> Install workflow module and start using it.

This is not enough steps to reproduce this bug. "start using it" doesn't help someone like me who never uses this module and therefore doesn't know at what step this is likely to trigger. :p

But you've given proper steps in the PR so I'll just copy those in here for you.

**Comment by GuySartorelli** [comment]
That said, I'm unable to reproduce this bug using those reproduction steps on a fresh installation of `silverstripe/installer` with this module added.

Can you please:
1. Confirm you did in fact reproduce this in a fresh installation
2. Clarify what needs to be in the "basic workflow"
3. Add any additional steps that might be missing (even if it seems trivial) - I only follow the exact steps as provided, so there may be something you're doing that seems obvious to you but which I haven't done

**Comment by satrun77** [comment]
I have updated the steps. 

yes, I have tested it in a fresh installer. I have one just for that :) 

Reading the code the argument is incorrect. They are matching the old style.

**Comment by satrun77** [comment]
My bad steps are not correct :) 

I will test it and give correct steps, but the code still wrong

**Comment by satrun77** [comment]
Update the steps. :)

**Comment by GuySartorelli** [comment]
Thanks for reporting and fixing that. It'll be automatically tagged by GitHub actions.
