### ISSUE TITLE
Too many unwanted icons visible in workflow manage interface

### ISSUE THREAD

**Issue by satrun77** [silverstripe-australia/advancedworkflow#515]
### Module version(s) affected

6.1.1

### Description

Install workflow and add a new one you see this
<img width="1057" alt="Screenshot 2024-01-25 at 12 13 13 PM" src="https://github.com/symbiote/silverstripe-advancedworkflow/assets/166450/75d55bca-4c03-4c68-861e-2c802b916057">

Which seems related to Similar issue in https://github.com/silverstripe/silverstripe-admin/pull/1581

### How to reproduce

- Add a workflow and select the default template
- Save and see the extra icons

### Possible Solution

Remove data-icon from the template

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
Thanks for reporting and fixing this.
The PR has been merged and it will be automatically tagged by GitHub Actions.
